#!/bin/zsh
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
export XDG_RUNTIME_DIR=/run/user/1000
export DISPLAY=$(dig +noall +answer $(hostname -s) | tail -1 | cut -f 5):0.0
export XMODIFIERS=@im=gcin
export GTK_IM_MODULE=gcin
export QT_IM_MODULE=gcin
export LIBGL_ALWAYS_INDIRECT=1
export PULSE_SERVER=tcp:$(dig +noall +answer $(hostname -s) | tail -1 | cut -f 5)
i3 -c ~/.config/i3/config_preload > /dev/null 2>&1 &
xrdb -merge ~/.Xresources
xrandr --setmonitor HDMI1 1919/307x1080/177+0+0 default
xrandr --setmonitor HDMI2 1920/307x515/83+0+1080 none
feh --bg-scale /home/wayne/DSC_1245.JPG
sleep 0.5
pkill i3
picom -b
i3 -c ~/.config/i3/config_dual >/dev/null &
